### PR TITLE
Add separate list for hosts that needs to be removed

### PR DESCRIPTION
**Pull request by Cougar**
If any hostname needs to be removed, add it to the removed_hosts list.
Old entries can be removed. This makes the task faster and avoids
missing hostnames during the run of playbook

### CODE REVIEW

**Comment by franklinkim** [comment]
hi, i don't like the concept of having a `removed_hosts` variable. The regular convention would be the mark a `hosts` entry as sth like `state: absent` ie:

```
hosts:
  - { ip: '127.0.0.1', domain:'foobar.com', state: absent }
```
Since if your using only this role to manage your hosts entries I figured it would be more convenient to just remove all hosts first and add all the given ones again. Don't know how many entries you have but I don't think that's much of a performance issue...

What exactly do you mean by "avoids
missing hostnames during the run of playbook"

**Comment by Cougar** [comment]
My idea was to add new hosts to the `hosts` list and when any of them needs to be removed, then just move the line to the `removed_hosts` which is very simple task. Later on it can be removed completely but it doesn't harm if it stays in this list (only makes task runtime longer).

Right now I see that the problem is even bigger and I actually didn't fix that properly (I'll prepare change later on). `tasks/reset.yml` removes always **all** existing hosts and does it as many times as many are hosts in the list (`with_items: hosts`). During this time there will be no hosts in `/etc/hosts` file. With long list of hosts, this takes also long time. This is why I saw big win because my `removed_hosts` list was very short.

After that `tasks/add.yml` adds them back one by one. All hosts will be back after this task finishes.

In my case the link between management station and server is not very fast. I see noticeable delay and the whole process takes sometimes up to minute. Half of this time the `/etc/hosts` file is completely empty (ie doesn't have entries added by Ansible) and then some systems start failing with the name lookup.


https://github.com/mivok/ansible-users works similar way (lists `users` and `users_deleted`)

**Comment by franklinkim** [comment]
Ah, now I see what you mean. 
The iteration shouldn't have been there for the reset of cause! Missed that one, THX.

I added a `hosts_reset` variable to control the role's behavior and the `state` variable on each host item.
That should work for you now. 

NOTE: I renamed the tags so your comment on [galaxy](https://galaxy.ansible.com/detail#/role/1371) with "--skip-tags=reset" doesn't apply any more! Use the `hosts_reset: no` way.

Cheers

**Comment by Cougar** [comment]
Thanks! This is even better :+1:

**Pull request closed without merging**
